title: Awesome Generative AI Resources
description: Your ultimate hub for Generative AI resources, tools, and guides.
baseurl: "" # Leave this blank for custom domain
url: "http://brilliantaitools.com"

# Theme settings
remote_theme: poole/hyde
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Resources
    url: /resources/

# Social links
social_links:
  - name: GitHub
    url: https://github.com/zacfrulloni/Awesome-Generative-AI-Resources
  - name: BuyMeACoffee
    url: https://www.buymeacoffee.com/zazacattack

# Build settings
markdown: kramdown
