# Site Metadata
title: Awesome Generative AI Resources
description: Welcome to the Awesome Generative AI Hub! This repository is a curated resource for anyone interested in learning and utilising the latest generative AI applications.
url: "https://github.com/zacfrulloni/Awesome-Generative-AI-Resources/"
baseurl: "/Awesome-Generative-AI-Resources"

author:
  name: Zac Frulloni
  email: zacfrull@hotmail.com

# Theme Configuration
theme: minima

# Plugins (Optional but Recommended)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-theme-minima

# Exclude Files from Processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
