# Site Metadata
title: Prompt Engineering Holy Grail
description: A comprehensive resource for prompt engineering best practices and techniques.
url: "https://github.com/zacfrulloni/Awesome-Generative-AI-Resources/"
baseurl: "/Awesome-Generative-AI-Resources"

author:
  name: Zac Frulloni
  email: zacfrull@hotmail.com

# Theme Configuration
theme: minima

# Plugins (Optional but Recommended)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-theme-minima

# Exclude Files from Processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
